debug=false

[manager]
id = "ChangeMe"
name = "Filigran connector manager"
daemon = "portainer"

[opencti]
url = "http://localhost:4000/graphql"
token = "ChangeMe"
unsecured_certificate = false
with_proxy = false

[portainer]
api = "https://localhost:9443"
api_key = "ChangeMe"
api_version = "v1.41"
env_id = "3"
env_type = "docker" # only docker supported
stack = "opencti-dev"

[kubernetes]
api = "https://localhost:9443"