apiVersion: v1
kind: ServiceAccount
metadata:
  name: connector-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: connector-manager
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "update", "patch", "deletecollection"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cm-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: connector-manager
subjects:
  - kind: ServiceAccount
    name: connector-manager